#!/usr/bin/env python3
"""
Configuration Generator for FreeRTOS Precise Scheduler
Generates C code from JSON configuration files
"""

import json
import sys
import os

# Task types matching the C enum
HARD_RT = 0
SOFT_RT = 1


def load_config(filename):
    """Load configuration from JSON file"""
    with open(filename, 'r') as f:
        return json.load(f)


def save_config(config, filename):
    """Save configuration to JSON file"""
    with open(filename, 'w') as f:
        json.dump(config, f, indent=2)


def check_schedulability(config):
    """
    Check if the configuration is valid and schedulable.
    Returns (is_valid, list_of_errors, list_of_warnings)
    """
    errors = []
    warnings = []
    major_frame = config.get('major_frame_ticks', 1000)
    tasks = config.get('tasks', [])
    
    # Get only HRT tasks for overlap checking
    hrt_tasks = [t for t in tasks if t['task_type'] == 'HARD_RT']
    
    # Check each task
    for task in tasks:
        name = task['name']
        start = task['start_time']
        end = task['end_time']
        
        # Check time bounds
        if start < 0:
            errors.append(f"{name}: start_time cannot be negative")
        
        if start >= end:
            errors.append(f"{name}: start_time ({start}) must be less than end_time ({end})")
        
        if end > major_frame:
            errors.append(f"{name}: end_time ({end}) exceeds major frame ({major_frame})")
    
    # Check HRT overlaps
    for i in range(len(hrt_tasks)):
        for j in range(i + 1, len(hrt_tasks)):
            t1 = hrt_tasks[i]
            t2 = hrt_tasks[j]
            
            # Two intervals overlap if: start1 < end2 AND start2 < end1
            if t1['start_time'] < t2['end_time'] and t2['start_time'] < t1['end_time']:
                errors.append(
                    f"HRT overlap: {t1['name']} [{t1['start_time']}-{t1['end_time']}] "
                    f"and {t2['name']} [{t2['start_time']}-{t2['end_time']}]"
                )
    
    # Calculate utilization
    total_hrt = sum(t['end_time'] - t['start_time'] for t in hrt_tasks)
    utilization = (total_hrt / major_frame) * 100
    
    if utilization > 90:
        warnings.append(f"HRT utilization is {utilization:.1f}% - not much room for SRT tasks")
    
    is_valid = len(errors) == 0
    return is_valid, errors, warnings


def print_analysis(config):
    """Print schedulability analysis results"""
    major_frame = config.get('major_frame_ticks', 1000)
    tasks = config.get('tasks', [])
    hrt_tasks = [t for t in tasks if t['task_type'] == 'HARD_RT']
    srt_tasks = [t for t in tasks if t['task_type'] == 'SOFT_RT']
    
    total_hrt = sum(t['end_time'] - t['start_time'] for t in hrt_tasks)
    utilization = (total_hrt / major_frame) * 100
    
    print("\n" + "=" * 50)
    print("  SCHEDULABILITY ANALYSIS")
    print("=" * 50)
    print(f"  Major Frame: {major_frame} ticks")
    print(f"  Tasks: {len(tasks)} total ({len(hrt_tasks)} HRT, {len(srt_tasks)} SRT)")
    print(f"  HRT Utilization: {utilization:.1f}%")
    
    is_valid, errors, warnings = check_schedulability(config)
    
    if errors:
        print(f"\n  ERRORS:")
        for e in errors:
            print(f"    - {e}")
    
    if warnings:
        print(f"\n  WARNINGS:")
        for w in warnings:
            print(f"    - {w}")
    
    print("\n" + "=" * 50)
    if is_valid:
        print("  RESULT: OK - Configuration is schedulable")
    else:
        print("  RESULT: FAILED - Fix errors above")
    print("=" * 50 + "\n")
    
    return is_valid


def generate_header(config):
    """Generate the .h file content"""
    tasks = config.get('tasks', [])
    
    code = """/*
 * Generated Configuration Header
 * Auto-generated by config_generator.py - do not edit manually
 */

#ifndef GENERATED_CONFIG_H
#define GENERATED_CONFIG_H

#include "scheduler_config.h"

/* Task function prototypes */
"""
    
    for task in tasks:
        code += f"void {task['function_name']}(void* pvParameters);\n"
    
    code += f"""
/* Configuration */
extern TimelineTaskConfig_t xGeneratedTasks[];
extern TimelineConfig_t xGeneratedConfig;

#define GENERATED_TASK_COUNT {len(tasks)}

#endif
"""
    return code


def generate_source(config):
    """Generate the .c file content"""
    tasks = config.get('tasks', [])
    
    code = """/*
 * Generated Configuration Source
 * Auto-generated by config_generator.py - do not edit manually
 */

#include "generated_config.h"

TimelineTaskConfig_t xGeneratedTasks[] = {
"""
    
    for i, task in enumerate(tasks):
        task_type = "HARD_RT" if task['task_type'] == 'HARD_RT' else "SOFT_RT"
        comma = "," if i < len(tasks) - 1 else ""
        stack = task.get('stack_depth', 128)
        
        code += f"""    {{
        .pcTaskName = "{task['name']}",
        .pxTaskFunction = {task['function_name']},
        .xType = {task_type},
        .ulStart_time = {task['start_time']},
        .ulEnd_time = {task['end_time']},
        .ulSubframe_id = {task['subframe_id']},
        .usStackDepth = {stack}
    }}{comma}
"""
    
    code += f"""}};

TimelineConfig_t xGeneratedConfig = {{
    .pxTasks = xGeneratedTasks,
    .ulNumTasks = {len(tasks)}
}};
"""
    return code


def generate_stubs(config):
    """Generate stub task functions"""
    tasks = config.get('tasks', [])
    
    code = """/*
 * Task Function Stubs
 * Replace these with your actual implementations
 */

#include "FreeRTOS.h"
#include "task.h"
#include "generated_config.h"

"""
    
    for task in tasks:
        task_type = "HRT" if task['task_type'] == 'HARD_RT' else "SRT"
        code += f"""/* {task['name']} - {task_type} [{task['start_time']}-{task['end_time']}] */
void {task['function_name']}(void* pvParameters)
{{
    (void)pvParameters;
    /* TODO: implement task logic */
}}

"""
    return code


def generate_code(config, output_dir):
    """Generate all C files"""
    os.makedirs(output_dir, exist_ok=True)
    
    # Write header
    with open(os.path.join(output_dir, 'generated_config.h'), 'w') as f:
        f.write(generate_header(config))
    print(f"  Created: {output_dir}/generated_config.h")
    
    # Write source
    with open(os.path.join(output_dir, 'generated_config.c'), 'w') as f:
        f.write(generate_source(config))
    print(f"  Created: {output_dir}/generated_config.c")
    
    # Write stubs
    with open(os.path.join(output_dir, 'task_stubs.c'), 'w') as f:
        f.write(generate_stubs(config))
    print(f"  Created: {output_dir}/task_stubs.c")


def interactive_mode():
    """Create configuration interactively"""
    print("\n=== FreeRTOS Scheduler Configuration ===\n")
    
    # Get major frame
    try:
        major_frame = input("Major frame (ticks) [1000]: ").strip()
        major_frame = int(major_frame) if major_frame else 1000
    except:
        major_frame = 1000
    
    config = {
        'major_frame_ticks': major_frame,
        'tasks': []
    }
    
    print("\nAdd tasks (empty name to finish):\n")
    
    task_num = 1
    while True:
        print(f"--- Task {task_num} ---")
        name = input("  Name: ").strip()
        if not name:
            break
        
        func = input(f"  Function name [v{name}Task]: ").strip()
        if not func:
            func = f"v{name}Task"
        
        ttype = input("  Type (HRT/SRT) [HRT]: ").strip().upper()
        if ttype not in ['HRT', 'SRT']:
            ttype = 'HRT'
        
        try:
            start = int(input("  Start time: ").strip())
            end = int(input("  End time: ").strip())
            subframe = input("  Subframe [0]: ").strip()
            subframe = int(subframe) if subframe else 0
            stack = input("  Stack size [128]: ").strip()
            stack = int(stack) if stack else 128
        except:
            print("  Invalid input, skipping...\n")
            continue
        
        config['tasks'].append({
            'name': name,
            'function_name': func,
            'task_type': 'HARD_RT' if ttype == 'HRT' else 'SOFT_RT',
            'start_time': start,
            'end_time': end,
            'subframe_id': subframe,
            'stack_depth': stack
        })
        
        print(f"  Added {name}\n")
        task_num += 1
    
    return config


def create_example():
    """Create an example configuration file"""
    config = {
        'major_frame_ticks': 1000,
        'tasks': [
            {
                'name': 'SensorRead',
                'function_name': 'vSensorReadTask',
                'task_type': 'HARD_RT',
                'start_time': 0,
                'end_time': 50,
                'subframe_id': 0,
                'stack_depth': 256
            },
            {
                'name': 'DataProcess',
                'function_name': 'vDataProcessTask',
                'task_type': 'HARD_RT',
                'start_time': 100,
                'end_time': 200,
                'subframe_id': 1,
                'stack_depth': 512
            },
            {
                'name': 'Actuator',
                'function_name': 'vActuatorTask',
                'task_type': 'HARD_RT',
                'start_time': 300,
                'end_time': 400,
                'subframe_id': 2,
                'stack_depth': 256
            },
            {
                'name': 'Logging',
                'function_name': 'vLoggingTask',
                'task_type': 'SOFT_RT',
                'start_time': 0,
                'end_time': 1000,
                'subframe_id': 0,
                'stack_depth': 128
            }
        ]
    }
    return config


def print_usage():
    print("""
Usage: python3 config_generator.py [options]

Options:
  -i, --interactive     Create config interactively
  -f, --file FILE       Load config from JSON file
  -g, --generate        Generate C code
  -o, --output DIR      Output directory (default: generated)
  -s, --save FILE       Save config to JSON file
  --example             Create example config file
  -h, --help            Show this help

Examples:
  python3 config_generator.py --example --save my_config.json
  python3 config_generator.py -f my_config.json
  python3 config_generator.py -f my_config.json -g -o output/
  python3 config_generator.py -i -s new_config.json -g
""")


def main():
    # Simple argument parsing (no argparse to keep it simple)
    args = sys.argv[1:]
    
    if not args or '-h' in args or '--help' in args:
        print_usage()
        return 0
    
    config = None
    output_dir = 'generated'
    do_generate = False
    save_file = None
    
    i = 0
    while i < len(args):
        arg = args[i]
        
        if arg in ['-i', '--interactive']:
            config = interactive_mode()
        
        elif arg in ['-f', '--file']:
            i += 1
            if i < len(args):
                config = load_config(args[i])
                print(f"Loaded: {args[i]}")
        
        elif arg in ['-g', '--generate']:
            do_generate = True
        
        elif arg in ['-o', '--output']:
            i += 1
            if i < len(args):
                output_dir = args[i]
        
        elif arg in ['-s', '--save']:
            i += 1
            if i < len(args):
                save_file = args[i]
        
        elif arg == '--example':
            config = create_example()
            print("Created example configuration")
        
        i += 1
    
    if config is None:
        print("Error: No configuration loaded. Use -f or -i or --example")
        return 1
    
    # Save if requested
    if save_file:
        save_config(config, save_file)
        print(f"Saved: {save_file}")
    
    # Always run analysis
    is_valid = print_analysis(config)
    
    # Generate code if requested and valid
    if do_generate:
        if is_valid:
            print("Generating C code...")
            generate_code(config, output_dir)
            print("Done!")
        else:
            print("Cannot generate code - fix errors first")
            return 1
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
